### ISSUE TITLE
atom-discord fails to work on Linux

### ISSUE THREAD

**Issue by szymex73** [HelloWorld017/atom-discord#10]
I have Linux Mint 18.2, latest Discord, latest Atom and latest atom-discord.
No matter what process for atom I select, no rich presence is shown

**Comment by Zoddo** [comment]
There was an updated pushed few hours ago who fixed it. Have you update?

**Comment by szymex73** [comment]
I installed it 10 minutes before creating this issue, so I have the latest version

**Comment by Zoddo** [comment]
You have added Atom in the game list of Discord?

**Comment by szymex73** [comment]
I tried every Atom process. I already said that in first message

**Comment by HelloWorld017** [comment]
Please try running atom in terminal and upload the console output.

**Comment by qoutsie** [comment]
Weird issue , as this worked for me before update and is now broken :confused: .....

**Comment by HelloWorld017** [comment]
Do you mean v1.3.0?

**Comment by szymex73** [comment]
It looks like you need to delete all previous RPC/presence apps/processes from Discord and then wait for the RPC from Atom ot show up. If it doesn't show up you need to either restart Discord or Atom. Then it should work. It works for me.
