### ISSUE TITLE
Rich Presence Doesn't pop up in discord on Elementary OS 5.1 (Based on Ubuntu)

### ISSUE THREAD

**Issue by Maitreya29** [HelloWorld017/atom-discord#100]
![Image of Problem](https://i.imgur.com/cVDCHJm.png)

## Step to reproduce
1.   Install Atom-Discord on Elementary OS 5.1 (first installed via snap but I later deleted and installed via deb as the faq suggested)
2.   Add ATOM to discord games

## Information
**Platform**: Elementary OS 5.1
**Atom**: 1.48.0
**Package Version**: 2.0.2

### Non-Core Packages
```
Script 3.26.0
Atom-Discord 
```

**Comment by Maitreya29** [comment]
fuck this, vscode is better

**Comment by PCelestia** [comment]
atom is better imo

for me what i had to do is open discord first and DONT ADD IT AS GAME, then launch atom and it worked without doing anything else. if u add as game i think it overrides the rich presence thing
