### ISSUE TITLE
Installing the plugin reveals an error

### ISSUE THREAD

**Issue by itsnotjasper** [HelloWorld017/atom-discord#101]
**Please use this template only if the issue related to Error / Unexpected behavior**  
**Please use suitable tags**

## Step to reproduce
1.   Windows 10
2.   Install the atom discord plugin
3.   Wait for it to end
4.   Error message at 'plugins' and 'install' tabs

## Information
OS: Windows

     events.js:174

      throw er; // Unhandled 'error' event
      ^

      Error: ENOENT: no such file or directory, open 'C:\Users\Jasper\.atom\packages\atom- 
     discord\node_modules\sockjs\lib\chunking-test.js'
      Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:734:7)

    at WriteStream.emit (events.js:198:13)

    at C:\Users\Jasper\AppData\Local\atom\app-1.48.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:303:14

    at C:\Users\Jasper\AppData\Local\atom\app-1.48.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:333:16

    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
### Non-Core Packages
```
Hydrogen
```

**Comment by HelloWorld017** [comment]
If you don't mind, please try the installation from source code as the dependency of atom-discord is not well-managed currently

**Comment by itsnotjasper** [comment]
Trailing issue that I'm annoyed by
