### ISSUE TITLE
Atom-Discord detects Atom's background process and keeps the RichPresence

### ISSUE THREAD

**Issue by TheOnlyArtz** [HelloWorld017/atom-discord#11]
Hey there! First of all, this is a super cool package for Atom
But... There's a bug, We know that when we're closing Atom there's a background process that runs for Updates and Booting the software faster. Atom-Discord detects those and thinks I'm still inside Atom, so the RichPresence will never get off my profile

**Comment by Zoddo** [comment]
hmm... That's weird, when I close Atom, there is not processes remaining.

Maybe this is provided by some kind of packages?

**Comment by HelloWorld017** [comment]
Okay, I'll add expire time when next commit.

**Comment by HelloWorld017** [comment]
I found out that adding endTimestamp only makes elapsed to left.
I think the fundamental solution is tracking opened windows.

**Comment by Mdstumpfy123** [comment]
I have this same problem and it is still not working correctly and there is no background process on my pc and it is still going.

**Comment by HelloWorld017** [comment]
If there is no background process, it may bug of Discord. Because Discord detects process and only shows Rich Presence of `running process`.

**Comment by TheOnlyArtz** [comment]
That's so weird I got some. Maybe external packages?

**Comment by HelloWorld017** [comment]
Is the issue have solved?

**Comment by HelloWorld017** [comment]
I added a code to destroy RPC Client properly.

**Comment by TheOnlyArtz** [comment]
Nice! It's solved

**Comment by HelloWorld017** [comment]
I can't find out the reason this error is occured.

**Comment by HelloWorld017** [comment]
According to Hallo89 (#24), there's a brief moment that Discord detects not playing. When I record log output, after destroying RPC Client, the Discord detects not playing and although neither packets are sent nor reopened RPC, Discord detects I am playing again.

**Comment by HelloWorld017** [comment]
Maybe removing inactivity packet help solving this issue.

**Comment by TheOnlyArtz** [comment]
That can be reasonable, can't you just destroy the client when Atom shuts down?

**Comment by Hallo89** [comment]
It also appears that sometimes this issue doesn't appear, but I can't see what exactly triggers it.
I have some theses for this:
1. Somehow the API's react time overlaps in a different way than usual, so this bug _doesn't_ happen
2. It's something to do with how the rich presence is handled within the 'games' tab in Discord (as it's just a blank space, idk
3. A friend told me that also Osu has a problem kind of like this, when one closes the game, Discord still shows "playing: Osu", but with rich presence (showing 'idle'), so maybe it is a problem on Discord's side after all

Now, I have no idea of programming beside html/css, so this might sound stupid, but I hope this helps anyway ^^

**Comment by TheOnlyArtz** [comment]
Sorry to make you get bad but HTML / CSS aren't programming languages, and if you think about it deeply, JavaScript isn't too, HTML is a markup language and JavaScript is a scripting language

**Comment by Hallo89** [comment]
... I do know that by all means

**Comment by TheOnlyArtz** [comment]
![image](https://user-images.githubusercontent.com/30025874/33680273-bee9a9a2-dac9-11e7-8240-567a173b9dd9.png)
Well... Looks like it fucks up even more now @HelloWorld017

**Comment by Hallo89** [comment]
What's different? That's exactly what this issue consist of

**Comment by TheOnlyArtz** [comment]
No, The issue was the rich presence was still on, now it's just the name

**Comment by Hallo89** [comment]
Yeah okay, but I pointed it out earlier :D 
see #24

**Comment by arten1337** [comment]
![screenshot from 2018-08-11 20-45-37](https://user-images.githubusercontent.com/38775423/43993215-b0380178-9da7-11e8-8aaf-fd80501077e2.png)
it only shows this for me
