### ISSUE TITLE
custom image not support url

### ISSUE THREAD

**Issue by ID29TH** [HelloWorld017/atom-discord#144]
![Screenshot_2](https://user-images.githubusercontent.com/6857480/181462828-03046112-a8aa-434b-baf0-9b74bf453768.png)

![Screenshot_3](https://user-images.githubusercontent.com/6857480/181462885-750c1d40-3b0a-463b-9519-0fd16ad5d710.png)

I think custom image should support url because from my test it can put url , can you adjust and make it support ?

**Comment by ShadowLp174** [comment]
Sadly, this doesn't work with Discords system... The image has to be an asset set in the (discord) app. The key you can enter here is just the name of the asset so discord knows which of your uploaded pictures to choose.

**Comment by ShadowLp174** [comment]
The video you sent is quite interesting... Though it seems that image urls are some undocumented feature. The discord tool for rich presence does not allow non-asset inputs. I'll have a look at it when I get home

**Comment by ID29TH** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/6857480/181633373-d6a1fbd2-92ce-433c-b852-cd127536dc66.png)

I tested with nodejs.
it can work well

**Comment by ShadowLp174** [comment]
Does it work in the atom package now?

**Comment by ID29TH** [comment]
I think it works Because I didn't customize anything, just use the image url, but your plugin, I'm not sure when choosing custom, how does package implement the value ?

**Comment by ID29TH** [comment]
Now package atom-discord doesn't work.

**Comment by ID29TH** [comment]
I don't know if the developer will try to fix or check ?

**Comment by ShadowLp174** [comment]
Depending on the code of the package I'll try to implement it... It's still open source :)
