### ISSUE TITLE
energy impact ⚡️

### ISSUE THREAD

**Issue by marclundgren** [HelloWorld017/atom-discord#19]
I just spent about an hour diagnosing my Atom's high energy consumption and narrowed it down to this package. Discord was not open when I ran these tests.

I've got about 40 community packages combined. The total energy consumption saved when I disabled this package was about 2700% more efficient with `atom-discord` disabled.

:(

**Comment by marclundgren** [comment]
Looks like we're polling a remote endpoint on this line, which is likely the culprit for a high energy impact:

https://github.com/HelloWorld017/atom-discord/blob/master/src/send-discord.js#L87

**Comment by marclundgren** [comment]
A package configuration option for the poll interval (currently set to 3 seconds) is probably the easiest/quickest way to provide a solution that works for everyone.

**Comment by TheOnlyArtz** [comment]
Well, I won't target `Atom-Discord` but what I would do, Is opening an issue on (Atom)[https://github.com/atom/atom]
We all know that Atom is not that good when it comes to CPU usage and performance in general but somehow we will never stop love this JavaScript masterpiece

Anyways, being with 40 community packages which I can tell that most of them are doing some front-end stuff
Will slowdown Atom nowhere near like backend work like `Atom-Discord` does. It isn't something new that backend is always slower than something that happens on your machine 😄 
Hoped I've clarified some things

**Comment by TheOnlyArtz** [comment]
Oh the [interval](https://github.com/HelloWorld017/atom-discord/blob/master/src/send-discord.js#L87) you're talking about shouldn't be like that and I can agree on that. I will make a pull request and see how it goes.

**Comment by HelloWorld017** [comment]
Setting interval is already in settings (added at 4236d9a0914738d79f686f02dd267355b60b8159)

**Comment by TheOnlyArtz** [comment]
That is still wrong @HelloWorld017 I'm making a PR right now to clarify things.

**Comment by TheOnlyArtz** [comment]
[#20](https://github.com/HelloWorld017/atom-discord/pull/20)

**Comment by HelloWorld017** [comment]
I really appreciate your contribution!

**Comment by TheOnlyArtz** [comment]
No problem, I'm just here to help some good ideas, glad that is you to make it and not some guy who won't listen to his users

**Comment by TheOnlyArtz** [comment]
@marclundgren I hope [#20](https://github.com/HelloWorld017/atom-discord/pull/20) will make your PC to feel better 😄

**Comment by TheOnlyArtz** [comment]
@marclundgren @HelloWorld017 Can one of you close this issue please?
