### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by yamboy1** [HelloWorld017/atom-discord#2]
How do I use this? i'm confused

**Comment by HelloWorld017** [comment]
1. Please install atom-discord on Atom.
2. Please add Atom in discord game list.
3. When you run Atom, what you are coding will be shown in Discord.

**Comment by yamboy1** [comment]
I tried that, I guess that this just doesn't work with the linux discord client

**Comment by HelloWorld017** [comment]
I guess removing window registry regstering may help this issue.
I'll fix on next commit.

**Comment by HelloWorld017** [comment]
May be fixed on f4094544e80a75d2a1e3721a3ba8584704b350a1

**Comment by yamboy1** [comment]
Okay, I'll test it when I get home
