### ISSUE TITLE
What what happened to "Editing a %type% file"?

### ISSUE THREAD

**Issue by TheOnlyArtz** [HelloWorld017/atom-discord#22]
What what happened to "Editing a %type% file"?
- It was a good reference.
- And now when it says `Editing name.extension` doesn't look clean, even messy

**Comment by HelloWorld017** [comment]
Would you explain more about issue?

**Comment by TheOnlyArtz** [comment]
Yes

**Comment by TheOnlyArtz** [comment]
It should be exactly like it was in 1.3

**Comment by HelloWorld017** [comment]
I'll add it to configuration

**Comment by TheOnlyArtz** [comment]
Thank you

**Comment by HelloWorld017** [comment]
a3dea3e3fb317e8044ea2cde5abf759fa16aa4a9
