### ISSUE TITLE
Elapsed time stuck on 00:00

### ISSUE THREAD

**Issue by TheOnlyArtz** [HelloWorld017/atom-discord#25]
Elapsed time stuck on 00:00

EDIT: Seems like it's like that for my friend and not for me.
![image](https://user-images.githubusercontent.com/30025874/33561908-9ce972aa-d91c-11e7-9114-8b0f4db1ac9e.png)

**Comment by HelloWorld017** [comment]
That's weird, because discord uses `started time` and calculate elapsed time.
