### ISSUE TITLE
I can't install it from amp

### ISSUE THREAD

**Issue by JuanM04** [HelloWorld017/atom-discord#28]
Hi, when I installed atom-discord I had this issue.

> Failed to install atom-discord because Git was not found.

> The atom-discord package has module dependencies that cannot be installed without Git.

> You need to install Git and add it to your path environment variable in order to install this package.

> You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

> Run apm -v after installing Git to see what version has been detected.

But I have Git and GitHub desktop installed.

**Comment by HelloWorld017** [comment]
Could you describe exactly why it is not installed from apm?

**Comment by JuanM04** [comment]
Supposedly it's because I don't have Git. But I have Git and GitHub Desktop.

**Comment by HelloWorld017** [comment]
Hmm.. I meant that is there any error reports or error message, etc...

**Comment by JuanM04** [comment]
It's all. It's a CopyPaste

**Comment by HelloWorld017** [comment]
Oh, I think installing git, not github desktop is essential to install.

**Comment by JuanM04** [comment]
I have reinstalled git yet.

**Comment by JuanM04** [comment]
But, I think that is a bluebird's problem

**Comment by HelloWorld017** [comment]
If you install this package via apm, the libraries (like blubird) should be installed automatically and I **strongly recommend** to do that.
But, if you download github release and copy to packages folder, you should install libraries by executing command `$ npm install` on the package directory. You can get npm by installing [node.js](https://nodejs.org)

**Comment by JuanM04** [comment]
But, I tried to install it with apm and then with npm. When I was installing blubird, the same fail message showed. So I tried to install another library (eg: express) and works.
