### ISSUE TITLE
The rich presence isn't working

### ISSUE THREAD

**Issue by Mdstumpfy123** [HelloWorld017/atom-discord#3]
After adding it to my game list it doesn't pop up

**Comment by Zoddo** [comment]
Hi. I have the same problem. Rich Presence doesn't shows up. Anything which can helps you to debug?

**Comment by HelloWorld017** [comment]
Please send me your Atom version, please. To send ipc on main process, this package uses some tricks, so I think it is maybe problem of the tricks.

**Comment by Mdstumpfy123** [comment]
My version is the latest (1.22.1)

**Comment by HelloWorld017** [comment]
Could you tell me your platform?

**Comment by PlayBy** [comment]
Version 1.22.1 
Windows 10 Home 64 bit

Doesn't work for me either.

**Comment by HelloWorld017** [comment]
Found not working on Atom 1.23.0-beta

**Comment by HelloWorld017** [comment]
The reason of the problem is that Discord.js uses String.prototype.padStart. I've added the polyfill and it might work.

Because the error was in atom main process, not renderer process, which most package work, the error was not shown in atom ui.

I added the polyfill in atom-discord 1.2.0.

**Comment by ihack2712** [comment]
I've found this not working on Mac OS X High Sierra 10.13.2, the package version is 1.5.1

**Comment by arten1337** [comment]
it doesn't shows up on discord. I am using Ubuntu 18.04, my atom version is 1.28.0.

**Comment by HelloWorld017** [comment]
Please follow [Checklist Here](https://github.com/HelloWorld017/atom-discord#checklist-when-rich-presence-is-not-showing).
