### ISSUE TITLE
Cannot find module 'discord-rpc'

### ISSUE THREAD

**Issue by marcyblaze** [HelloWorld017/atom-discord#31]
This module isn't installed on my computer. I can't install it with npm install because it says me

npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

What can I do?

**Comment by HelloWorld017** [comment]
please install git from git-scm.com

**Comment by marcyblaze** [comment]
I downloaded GitHub xD
Is GitHub needed or I can uninstall it?

**Comment by HelloWorld017** [comment]
Happy new year!
You should install Git. (It can be confused with GitHub. But, two programs are different program.) Please install git and try npm install again!
Uninstalling GitHub is not necessary.

**Comment by marcyblaze** [comment]
Perfect. Now it works. Thanks and happy new year to you! 😄
