### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by Ekidoxx** [HelloWorld017/atom-discord#32]
### Description
Few seconds after launching the editor, this package makes Atom slowly increasing used RAM until it's consuming about 2,1 GB of memory - while in my case, normally, Atom uses around 700 MB.
This makes whole editor either work amazingly slow, or even stuck at all...
<br />
### Environment informations
**Operating system:** Windows 7 Home Premium 64-bit SP1 with 12,0GB RAM
**Atom version:** 1.23.1
**Package version:** 1.4.0
**Startup time addition:** 355ms
**Reproduction rate:** 100%

**Comment by HelloWorld017** [comment]
Is anyone who has same error?

**Comment by Ekidoxx** [comment]
I recognized myself, that I didn't have this issue since the beginning of using Your package, so I thought I'd check if maybe Discord being launched has anything to do with the problem.
...and that's the test result:
<br />

| What                                                                        | RAM usage                |
|:-------------------------------------------------------:|:-----------------------:|
| Discord                                                                     | ~245 MB                   |
| Atom                                                                        | ~885 MB\*                |
| Discord _and_ Atom                                                 | ~250 MB / ~890 MB |
| Atom _with_ atom-discord package                        | ~2.350 MB                 |
| Discord _and_ Atom _with_ atom-discord package | ~245 MB / ~900 MB |

_\* Installed some more packages since creating this issue_

---

However, after I launched both Discord and Atom with the package, and then closed Discord, RAM usage didn't increase back to the ~2.350 MB as I expected.

So, to me it seems like the script(s) don't detect properly when to send rich presence information - and when incorrectly trying to send those into ether (as no Discord is running), it keeps looping something until being about to kill Atom. But that's just my thought, since I didn't understand even half the code :P

**Comment by HelloWorld017** [comment]
#35

**Comment by Hoi15A** [comment]
I can reproduce the issue exactly like @Ekidoxx described, the only difference that I have noticed in my case is that in addition to using up way more ram is that it also makes my CPU usage go up drastically (~125% according to `htop`)

<hr>

Here's some system information:
OS: `Arch Linux x86_64` (Kernel: `4.14.12-1-ARCH`)
RAM: `8GB`
Atom version: `1.23.2`
Package version: `1.4.0`

**Comment by Ekidoxx** [comment]
Hmm, I actually didn't even thought of checking CPU usage... Gonna check that once I have bit more free time

**Comment by TheSacredPixel** [comment]
Same here, easily reproducible by starting Atom w/ the package without Discord running, letting it steadily accumulate memory usage while at ~40%+ CPU usage, and watching both immediately dip to normal by launching Discord. Closing Discord at that point does not cause the issue to reoccur.

Specs:
OS: `Windows 10`
RAM: `8GB`
Atom version: `1.23.3`
Package version: `1.4.0`

**Comment by TheOnlyArtz** [comment]
Guys we need more information, can I ask you guys to test this issue while no tabs are being open except from the settings tab to enable/disable the package?

The reason for that is because Atom uses Electron and for every tab which you'll open another process will run in the background.

**Comment by HelloWorld017** [comment]
I suppose that IPC call when Discord is not running raised this error. So, I think checking is discord online using [ps-node](https://www.npmjs.com/package/ps-node) may help solving this error.

**Comment by GitSquared** [comment]
Started Atom with `atom-discord`. The package took 850ms to load, CPU usage stayed around 60 to 80% and RAM usage kept increasing until my system actually had to _use the swap space_. I could travel to the moon and back between when i opened a file and when Atom displayed it.

Clearly there is a memory leak somewhere.

Specs:
OS: Arch Linux _w/ Gnome_
RAM: 8GB + 4GB swap _(Atom used a total of 7GB before i shut it down)_
Latest version of everything.

**Comment by HelloWorld017** [comment]
When I tested two cases: with Discord and without Discord, I failed to reproduce this error. Maybe there is another factor to memory leak.

**Comment by Ekidoxx** [comment]
Any idea on what I/We could edit locally to check out if that would fix the issue?

**Comment by Ekidoxx** [comment]
@HelloWorld017 Are you sure you checked it with package version `1.4.0` and not with what's inside the master-branch?

Because once a weird thought came to me, I uninstalled the package, and then manually installed what's in this repo (as there were some commits that didn't get published under new release version) - and I'm surprised, but the bug has been fixed. So, how about You'd release `1.4.1`? :stuck_out_tongue:

**Comment by Ekidoxx** [comment]
@HelloWorld017 Are you sure that you have checked it with package version `1.4.0` and not with what's in master-branch?

Because once a weird thought came to me, I uninstalled the package and then manually installed it with content of this repo (as there were some commits that didn't get published under new release version) - And guess what, the bug has been fixed! :scream: 
So, how about You'd release `1.4.1`? :stuck_out_tongue:

**Comment by HelloWorld017** [comment]
I uploaded `1.5.0` to the apm! 😄 
Is anyone can confirm disappearance of this issue? 😆

**Comment by Hoi15A** [comment]
The issue still persists.
Atom drains memory and uses the CPU like crazy until discord is started.
![htop showing massive cpu & ram usage](https://i.neat.moe/8a5669c0704c0c72.png)

Closing discord again afterwards does not make the RAM be used up anymore.

The dev console in Atom does not show any errors while it is using up CPU and memory

**Comment by HelloWorld017** [comment]
Would you tell me if the memory leak happens on the renderer process?

**Comment by HelloWorld017** [comment]
Maybe dumping heap might help solving this issue.

**Comment by Ekidoxx** [comment]
Ok, with every next day it's getting more weird @HelloWorld017. After I updated the package through Atom, I again have this issue o.0'

**Comment by HelloWorld017** [comment]
I hope this bug happens to me

**Comment by HelloWorld017** [comment]
Would you get terminal output and check if this leak is happening on renderer process or on main process?

**Comment by Ekidoxx** [comment]
You mean by using one of these: [output-panel](https://atom.io/packages/output-panel) / [atom-terminal-panel](https://atom.io/packages/atom-terminal-panel)?

**Comment by HelloWorld017** [comment]
Umm... Actually I meant the cmd. If you open cmd at the directory where atom executable is and execute atom by cmd, you can see logs of atom.

**Comment by Ekidoxx** [comment]
Seems that I do something wrong, because I can't manage to get any log output anywhere... no output is created in command prompt, and no log file is created

**Comment by GitSquared** [comment]
@HelloWorld017 Seems like it's happening in the main process. I performed some tests using `htop` in a terminal:

Running Atom without `atom-discord` : 
![normal](https://user-images.githubusercontent.com/24496417/35337577-e330758e-011b-11e8-964f-aa4875417e5a.png)

After enable & restart : 
![rambug](https://user-images.githubusercontent.com/24496417/35337619-01e2065a-011c-11e8-9140-e20179db5f99.png)

When enabled, Atom's main process uses **60% of CPU** _(htop outputs the usage by core, so 150% CPU means a core and a half running at full speed)_ and eats about **30mb of RAM per second**, definitely a leak.

I'm going to try snooping around your code _('cuz i really want the darn thing to work)_. Can you confirm that you can't reproduce the issue on your end?

**Comment by HelloWorld017** [comment]
There is definitely a leak. But, I can't reproduce on my end and I'll upload screenshot and data next day. Anyway I am investigating the codes.

The reasons I thinking is
1. RPC Clients are keep created.
2. RPC Data is not sent properly and stored somewhere.
3. Regex which determines file type are keep created.

**Comment by HelloWorld017** [comment]
![Imgur](https://i.imgur.com/yV3tskS.gif)
atom-discord: Disabled

----
![Imgur](https://i.imgur.com/CipUnNb.gif)
atom-discord: Enabled
Discord Client: Turned on

----
![Imgur](https://i.imgur.com/jAQQHzm.gif)
atom-discord: Enabled
Discord Client: Turned off

**Comment by HelloWorld017** [comment]
Could anyone check this issue persists after f41c42963fc8135c29419a9f6a8368717cb2fd6f?

**Comment by mariosumd** [comment]
I had the problem, and now, after almost 45 minutes running, I had no leakage.

**Comment by xdavidhu** [comment]
Okey, I can reproduce this on macOS, and its really bad.

Atom with atom-discord with Discord turned off:
![screen shot 2018-01-30 at 17 24 13](https://user-images.githubusercontent.com/18151245/35577797-a304aba8-05e2-11e8-8b85-a06f03e4eb00.png)

Atom with atom-discord with Discord turned on: (No need to reboot Atom, just started Discord)
![screen shot 2018-01-30 at 17 27 59](https://user-images.githubusercontent.com/18151245/35577904-f2865bcc-05e2-11e8-8692-9e96021115c2.png)

Atom is totally unsable on a Mac if Discord is not running. Its lagging to the point that you can't even scroll/type... :/

**Comment by HelloWorld017** [comment]
Does this issue persist after setting interval to a very long-term?
If this issue related to sending IPC packets, it will disappear because ipc won't be sent because of very long interval.

**Comment by xdavidhu** [comment]
No, even if I set a big interval (60 000ms) the CPU is still at 100%.

But when I start Discord up, the CPU goes down to 1%.

**Comment by HelloWorld017** [comment]
That's interesting. I'll make start discord rpc client when the discord exists in the process list.

**Comment by vityavv** [comment]
Any progress on this issue? Still getting it on macOS
