### ISSUE TITLE
RAM Increasing over time

### ISSUE THREAD

**Issue by AlexFlipnote** [HelloWorld017/atom-discord#35]
**Hello there,**
Recently I have been taking usage of this wonderful package to show my friends what I do, however, there has been some issues with RAM growth, I made a GIF to showcase my issue.

## Enabled Package
![Image1](https://i.alexflipnote.xyz/ecf6db.gif)
## Disabled Package
![Image2](https://i.alexflipnote.xyz/2020f1.gif)

As shown from the two gifs provided above, when the package is enabled, it will grow the RAM usage.
If it helps to tell, the package doesn't work with Discord RPC at all, so I believe it is trying to use RPC but can't seem to do so.

Discord client: Discord Canary, Latest from 08/01/2018
Specs: 
![Image3](https://i.alexflipnote.xyz/6124f0.png)

Thanks in advance
-- AlexFlipnote

**Comment by HelloWorld017** [comment]
Is Discord turned on and Rich Presence is successfully showed? If not, maybe checking if discord is turned on and rpc is transfered to discord process help to fix this issue.

**Comment by HelloWorld017** [comment]
And, I'd be glad if you come to #32.

**Comment by AlexFlipnote** [comment]
Update on the case, turns out I just had to reboot Discord for RPC to work, my bad.
Apologies for the incorrect issue report, have a great day.
![Image](https://i.alexflipnote.xyz/2d2c54.png)
