### ISSUE TITLE
Rich Presence implementation fails

### ISSUE THREAD

**Issue by washingdone** [HelloWorld017/atom-discord#4]
The Rich presence implementation you're using doesn't actually work, None of this registry data actually functions, instead you should probably use discord-rpc on the npm list (https://www.npmjs.com/package/discord-rpc). for a successful implementation of this using another electron based editor check out https://github.com/maxerbox/vscode-discord

**Comment by HelloWorld017** [comment]
I am using `discord-rpc` on the npm registry and successfully tested on Atom 1.18.0. I'll checkout for vscode-discord to solve this problems.

**Comment by HelloWorld017** [comment]
Duplicate #3
