### ISSUE TITLE
Object.basename is deprecated.

### ISSUE THREAD

**Issue by wyysel** [HelloWorld017/atom-discord#43]
Reported from the atom deprecated calls panel, i didn't have this error before the last update:

*Arguments to `path.basename` must be strings*
```
Object.basename (C:\Users\User\AppData\Local\atom\app-1.21.1\resources\app.asar\src\electron-shims.js:31:10)
updateProjectName (C:\Users\User\.atom\packages\atom-discord\src\index.js:72:23)
atom.workspace.onDidChangeActiveTextEditor (C:\Users\User\.atom\packages\atom-discord\src\index.js:81:4)
Function.module.exports.Emitter.simpleDispatch (<embedded>:65955:20)
Emitter.emit (<embedded>:66071:34)
Workspace.didChangeActivePaneItemOnPaneContainer (<embedded>:27939:30)
```

**Comment by Ekidoxx** [comment]
When did it happen? Right after Atom loaded with file-tab, any other tab (i.e. settings) or with no tabs open?

**Comment by HelloWorld017** [comment]
`path.basename(atom.project.relativizePath(onlineEditor.buffer.file.path)[0])`

I should have checked the result of relativizePath.

**Comment by Ekidoxx** [comment]
@HelloWorld017 Ok, just got on my PC, and I can't manage to reproduce the error no matter what I try... ._.

@wyysel You'd mind sharing some more info about your working environment, like operating system, Atom version, and if it happens every time or just from time to time?

**Comment by HelloWorld017** [comment]
I found that `projectPath The String path to the project directory that contains the given path, or null if none is found.` from API documentation.

**Comment by wyysel** [comment]
@Ekidoxx @HelloWorld017 Sorry i couldn't answer you earlier. :/
Rn I still have the error (it started after i updated to the new version of your package the 23/01), and i didn't updated atom since that normally.
I am on windows 10 build 1709 (64-bits) and my atom is up to date V1.23.3
The rich presence seems working even i have the error, i shared it here only to let you know it, probably I am not the only one who have it.

The message shows immediately after i open a file: 
![image](https://user-images.githubusercontent.com/30549150/35399187-fe0fc21e-01f3-11e8-9121-c632f572c084.png)

Also the screenshot of the deprecation cop (the panel which opens when i click the little message above), it reported the bug here automatically when i clicked the "report issue" button:
![image](https://user-images.githubusercontent.com/30549150/35398867-3b5b39c4-01f3-11e8-85ea-64f430b7454f.png)
