### ISSUE TITLE
[suggestion] Customize working on message

### ISSUE THREAD

**Issue by ajgeiss0702** [HelloWorld017/atom-discord#46]
There should be an option where you can change what the working on message says. Even better, be able to set it for certain files.

The reason for this is because FileZilla's View/Edit will put it in an fz-temp folder, and then that is what is displayed as the working on.

**Comment by HelloWorld017** [comment]
Maybe it should implement per-project settings.

**Comment by DeadMasterBG** [comment]
Its done in 0325e94985bca28453fba77e0d7a3a8f2e759b5b soo..

**Comment by ajgeiss0702** [comment]
Thanks!
