### ISSUE TITLE
Latest Atom broke rich presence for me

### ISSUE THREAD

**Issue by jdamboeck** [HelloWorld017/atom-discord#53]
After updating to atom 1.26.0 discord wont show any details. Only Playing Atom Editor and the rich presence file icon.. bot nothing else anymore.

I am using Arch linux with the atom-editor-bin version.
![screenshot](https://user-images.githubusercontent.com/20957463/39398074-c483f368-4b08-11e8-8427-a715d7b11256.png)

**Comment by jdamboeck** [comment]
"atom-discord":
    behaviour:
      alternativeIcon: "atom-3"
      preferType: true
      showFilenameOnLargeImage: true
      updateTick: 150
      useRestIcon: false
    privacy: {}

**Comment by jdamboeck** [comment]
ive added a screenshot.. i mean the filetype icon at the username after Playing Atom Editor which you only see from rich presence enabled apps

**Comment by HelloWorld017** [comment]
Try restarting discord and atom.

**Comment by HelloWorld017** [comment]
If you come to official discord server, I'll try checking your rich presence is showing to other people.

**Comment by jdamboeck** [comment]
i restarted both many times.. reinstalled atom-discord, atom and discord.
what official discord server?

**Comment by HelloWorld017** [comment]
You could find it at the discord badge in readme file.
Please check if atom editor is added to game list.

**Comment by jdamboeck** [comment]
it is.. but does not show any info.
![screenshot_1](https://user-images.githubusercontent.com/20957463/39398326-60aa54fa-4b0c-11e8-901d-7e9d8badc25b.png)

**Comment by jdamboeck** [comment]
you mean thte dev server? 
https://discordapp.com/invite/discord-developers

**Comment by jdamboeck** [comment]
Just send me the link to the server plz. i dont know wich readme you mean
 :)

**Comment by HelloWorld017** [comment]
https://discord.gg/zfEs3K6
Here you are!
