### ISSUE TITLE
Package's not working

### ISSUE THREAD

**Issue by PhirosWolf** [HelloWorld017/atom-discord#55]
## Information
**Platform**: MacOS HighSierra 10.13.5
**Atom**: 1.27.2 x64
**Package Version**: 1.6.0

### Non-Core Packages
```
atom-beautify 0.32.5
atom-ide-ui 0.12.0
auto-update-packages 1.0.1
file-icons 2.1.21
highlight-selected 0.13.1
ide-csharp 0.6.2
minimap 4.29.8
minimap-find-and-replace 4.5.2
minimap-highlight-selected 4.5.2
pigments 0.40.2
teletype 0.13.3
```

Nothing in the console.

**Comment by HelloWorld017** [comment]
Please explain more about the issue

**Comment by PhirosWolf** [comment]
Yes.

**Comment by HelloWorld017** [comment]
Is there no console log when you started atom in console?

It looks like `Editor (hash) became online`.

**Comment by PhirosWolf** [comment]
No. `/Applications/Atom.app/Contents/MacOS/Atom` in the console doesn't return anything. But it launches Atom.

**Comment by HelloWorld017** [comment]
Are there any errors in developer tools console?
(Press ctrl-shift-i or ctrl-alt-i in Atom)

**Comment by PhirosWolf** [comment]
I have this : https://hastebin.com/hocituhujo.log

**Comment by HelloWorld017** [comment]
Thanks! For now, please install from source code. I'll update dependency to fix this issue.

**Comment by MineAle3** [comment]
I have the same problem, I got this error with the version compiled from source https://pastebin.com/YEHdafsN

**Comment by HelloWorld017** [comment]
Please update to 1.6.1
