### ISSUE TITLE
Elapsed time does not reset when reopening Atom

### ISSUE THREAD

**Issue by Davoleo** [HelloWorld017/atom-discord#66]
## Step to reproduce
1. Open Atom  
2. Close it
3. Reopen it

## Information
**Platform**: Windows 10
**Atom**: 1.31.1
**Package Version**: 1.6.1

### Non-Core Packages
```
ZenScript 0.2.5
Teletype 0.13.3
```

**Comment by HelloWorld017** [comment]
I found that some symptoms about it.

1. When it occurs, it occurs to everyone in a server.
2. Sometimes the time is normal for everyone.
3. The time is fixed to some strange time (about 17h ~ 19h)

**Comment by ihulsbus** [comment]
Same issue here. 

## Information
**Platform**: Mac OS 10.13.6
**Atom**: 1.31.2
**Package Version**: 1.6.1

### Non-Core Packages
```
autocomplete-clang  0.11.5
build  0.70.0
busy-signal 1.4.3
city-lights-syntax 1.1.8
city-lights-ui  1.5.3
file-icons  2.1.25
intentions  1.1.5
jackhammer-syntax  1.1.0
language-ini  1.20.0
language-latex  1.2.0
latex  0.50.0
latex-completions  0.3.5
linter  2.2.0
linter-gcc  0.7.1
linter-ui-default  1.7.1
pdf-view  0.71.0
platformio-ide  2.2.2 (disabled)
platformio-ide-debugger  1.2.6 (disabled)
platformio-ide-terminal  2.8.4
tool-bar  1.1.10
```

**Comment by TheAlgerianPrince** [comment]
I also have the same issue
![image](https://user-images.githubusercontent.com/7204422/47258127-92509800-d48e-11e8-92c0-15aade3db7b9.png)

**Comment by HelloWorld017** [comment]
Is anyone who has this problem after fbb66b9 ?

**Comment by TheAlgerianPrince** [comment]
I installed it yesterday from the Atom package installer menu which im guessing is the latest version so yes it would be after [`fbb66b9`](https://github.com/HelloWorld017/atom-discord/commit/fbb66b9a64aabe565f702e36f5e246a50ab15a58).

**Comment by HelloWorld017** [comment]
I didn't upload that commit to atom. So it must be before the commit.

**Comment by TheAlgerianPrince** [comment]
Ahh i see, you gonna upload that commit to atom?

**Comment by KlukCZ** [comment]
I opened the source code in atom and changed it as its showed in fbb66b9 and its working

**Comment by HelloWorld017** [comment]
Thx for testing! If there's no further bugs for more than some days, I'll upload it.
(It's because the bug doesn't occur sometimes)

**Comment by GeorgeCY2** [comment]
@KlukCZ thanks for letting us know, it actually solves the problem

**Comment by HelloWorld017** [comment]
Maybe related to [discordjs/RPC 4fd073](https://github.com/discordjs/RPC/commit/4fd07343f68758dc7873652b7e827ce91526782d)?

**Comment by ihulsbus** [comment]
Might be, but if I quickly look at it with fbb66b9 in mind it does not really make sense to me. Might be wrong though..

**Comment by HelloWorld017** [comment]
That commit changed the type: from float-point to integer
