### ISSUE TITLE
When I start Discord while Atom is already running I don't get the rich presence information.

### ISSUE THREAD

**Issue by AlexanderProd** [HelloWorld017/atom-discord#76]
When I start Discord while Atom is already running I don't get the rich presence information. I have to start Discord first. 
I'm using MacOS Mojave, Atom 1.32.1, and this plugin in version 2.0.1 .

**Comment by KlukCZ** [comment]
Restart atom

**Comment by AlexanderProd** [comment]
Thanks for the feedback.
