### ISSUE TITLE
"Atom Editor" is all that shows?

### ISSUE THREAD

**Issue by IngwiePhoenix** [HelloWorld017/atom-discord#78]
Hello! I am on MacOS and I wanted to use this package so people would stop getting on my case for replying only so slowly :) Unfortunately, this does not seem to work... My suspicion is that "Custom Client ID" is not set properly. I also get empty log files...?

```
Ingwie@Ingwies-Macbook-Pro.local /V/S/A/atom-discord $ wc log.txt 
       2       0       2 log.txt
```

Discord shows "Atom Editor" properly, but it doe snot seem to get the information to show stuff like "Working on %project%".

How can I get the Client ID of my instance so I can verify that the default actually matches?

**Comment by HelloWorld017** [comment]
First, for logging please check on the logging option in troubleshooting menu.
Second, if you want to use custom client, please set that to the App ID of `https://discordapp.com/developers/applications/`
