### ISSUE TITLE
Use the file-icons API if installed

### ISSUE THREAD

**Issue by dvdcd** [HelloWorld017/atom-discord#80]
File-icons is a great package for adding a ton of file type icons. It'd be great for making the file icon in RPC more unique by using it's api if it's installed.[More details here](https://github.com/file-icons/atom#integration-with-other-packages)

**Comment by HelloWorld017** [comment]
Atom-discord USES file-icons package. But, file-icons provide image as HTMLElement, not as image file. So, atom-discord pre-renders images using [icons.less](https://github.com/file-icons/atom/blob/master/styles/icons.less) in file-icons package.

You can see it at [fileicons-render](https://github.com/HelloWorld017/fileicons-render).
