### ISSUE TITLE
Variable could used at custom text on plugin configuration returns null when its value is not deployed.

### ISSUE THREAD

**Issue by seia-soto** [HelloWorld017/atom-discord#82]
## Step to reproduce
1.   Turn on the editor and go to plugin configuration
2.   Set custom text of Large Image as 'On %projectName%'
3.   On Discord, if project not opened, it shows null.

## Information
**Platform**: Win32_x64 - 10.17134
**Atom**: 1.34.0 x64
**Package Version**: 2.0.2

### Non-Core Packages
```
language-batchfile 0.7.5 (by mmins)
language-pug 0.0.22 (by genoma)
```

**Comment by Sqaaakoi** [comment]
I am also experiencing this, but with %fileName% in the state while idle

**Comment by HelloWorld017** [comment]
For idle state, please download branch `dev` and check if the issue is fixed.
For %projectName%, I'm working on it.

**Comment by HelloWorld017** [comment]
Could you try the latest `dev` branch?

**Comment by Seia-Soto** [comment]
> For idle state, please download branch `dev` and check if the issue is fixed.
> For %projectName%, I'm working on it.

Yes, I cloned dev branch into my local PC, and checked, but it is not updating the state after I changed the mode to custom. I don't sure it is working correctly.

**Comment by HelloWorld017** [comment]
Could you run atom from terminal and get logs?

**Comment by seia-soto** [comment]
Closing automatically due to inactivity.
