### ISSUE TITLE
Showing UNDEFINED-TRANSLATION in large image section and rest image

### ISSUE THREAD

**Issue by GamesProSeif** [HelloWorld017/atom-discord#83]
Comparing `src/config.js` and `i18n/enUS.json` files, translation of large image description and translation of rest description fails due to a type error. I would have pull requested this, but I don't have access to do so.

For fixing the problem, simply change the following lines in `i18en/enUS.json`

line 69
```js
"config-smallImage-desc": "Change content of large image on Rich Presence",
```

line 95
```js
"config-rest-description": "Change behaviour while you're resting",
```

to

line 69
```js
"config-largeImage-desc": "Change content of large image on Rich Presence",
```

line 95
```js
"config-rest-desc": "Change behaviour while you're resting",
```

And that's all, I checked the other files and I don't see them have these lines in theme anyways.

Edit:
I have managed to create a [pull request](https://github.com/HelloWorld017/atom-discord/pull/84) by forking the repository.

**Comment by HelloWorld017** [comment]
Fixed by #84
