### ISSUE TITLE
Doesn't work on Atom Nightly

### ISSUE THREAD

**Issue by shottei** [HelloWorld017/atom-discord#89]
## Problem
1. Doesn't work on Atom Nightly(tried to rewrite and..... didn't work)
2. Doesn't work on new Versions of Atom / Atom beta
3. Lacks Features

## Information
**Platform**: [Windows 7, 64x]  
**Atom**: [Atom Nightly]  
**Package Version**: [Tag(v1.42.0-beta0)]

### Non-Core Packages
```
Non
```

**Comment by HelloWorld017** [comment]
Duplicated: #88 

I will fix it in tomorrow :D
