### ISSUE TITLE
v1.2.0 failed to install

### ISSUE THREAD

**Issue by yamboy1** [HelloWorld017/atom-discord#9]
When I tried to install v1.2.0 it failed

![screenshot from 2017-11-25 18-57-41](https://user-images.githubusercontent.com/15204710/33227903-fc10e666-d212-11e7-873d-06557d910f04.png)

and

```
yamboy1@computer:~$ apm install atom-discord
Installing atom-discord to /home/yamboy1/.atom/packages ✗
undefined
`

**Comment by HelloWorld017** [comment]
Could you try 
`$ git clone https://github.com/HeloWorld017/atom-discord.git && cd atom-discord/ && apm link`
?

**Comment by yamboy1** [comment]
It installs, I haven't checked whether it works in discord yet

**Comment by yamboy1** [comment]
However it give me this error:

```
Set up discord RPC.
{ Error: connect ENOENT /run/user/1001/snap.atom/discord-ipc-0
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1001/snap.atom/discord-ipc-0' }
```

**Comment by yamboy1** [comment]
And the Rich Presence still doesn't work

**Comment by HelloWorld017** [comment]
Hmm... I think it may error of

**Comment by yamboy1** [comment]
But it won't be that part because I'm using Linux

**Comment by yamboy1** [comment]
ENOENT means `No such file or directory`

**Comment by yamboy1** [comment]
NVM IT WORKS!!!!!!

I think that my discord was broken.
